[versions]
# 工作系列
lombok-version = "1.18.30"
hutool-version = "5.8.11"
vavr-version = "0.10.4"
mapstruct-version = "1.4.2.Final"
guava-version = "23.0"
commons-lang3-version = "3.12.0"

# 日志
logback-version = "1.2.12"

# 测试
testng-version = "6.14.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
hutool-all = {module="cn.hutool:hutool-all",version.ref="hutool-version"}
vavr = {module="io.vavr:vavr",version.ref="vavr-version"}
mapstruct-mapstruct = {module="org.mapstruct:mapstruct",version.ref="mapstruct-version"}
mapstruct-jdk8 = {module="org.mapstruct:mapstruct-jdk8",version.ref="mapstruct-version"}
mapstruct-processor = {module="org.mapstruct:mapstruct-processor",version.ref="mapstruct-version"}
guava = {module="com.google.guava:guava",version.ref="guava-version"}
commons-lang3 = {module="org.apache.commons:commons-lang3",version.ref="commons-lang3-version"}

logback-classic = {module = "ch.qos.logback:logback-classic",version.ref = "logback-version"}

testng={module="org.testng:testng",version.ref="testng-version"}

[bundles]
mapstruct = ["mapstruct-mapstruct","mapstruct-jdk8","mapstruct-processor"]
logback = ["logback-classic"]

